"""Send GEO benchmark PDF report via email using SMTP settings from .env."""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import datetime
from config.settings import PROJECT_ROOT
from dotenv import load_dotenv

load_dotenv(PROJECT_ROOT / ".env")

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")


def send_report(pdf_path: str, to_email: str, run_date: str = None):
    """Send the PDF report as an email attachment."""
    if not all([SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD]):
        raise ValueError("SMTP settings not configured in .env")

    if run_date is None:
        run_date = datetime.now().strftime("%Y-%m-%d")

    msg = MIMEMultipart()
    msg["From"] = SMTP_USER
    msg["To"] = to_email
    msg["Subject"] = f"ON24 GEO Benchmark Report - {run_date}"

    body = f"""Hi Jayesh,

Your ON24 GEO Benchmark report for {run_date} is attached.

This report covers:
- Executive Summary with key wins and losses
- Share of Voice, Win Rate, Position, and Sentiment analysis across Grok, ChatGPT, and Claude
- Category performance breakdown
- Per-query search term analysis
- AI-generated tactical recommendations
- Citation analysis (www.on24.com vs event.on24.com)

Report generated by the ON24 GEO Benchmarking Tool.
"""
    msg.attach(MIMEText(body, "plain"))

    filename = os.path.basename(pdf_path)
    with open(pdf_path, "rb") as f:
        attachment = MIMEApplication(f.read(), _subtype="pdf")
        attachment.add_header("Content-Disposition", "attachment", filename=filename)
        msg.attach(attachment)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.send_message(msg)

    print(f"Report emailed to {to_email}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python -m reports.email_report <pdf_path> <to_email>")
        sys.exit(1)
    send_report(sys.argv[1], sys.argv[2])
